stages:
  - verify
  - deploy

include:
  - project: 'acquiring/devops/pipelines'
    ref: master
    file: '.checkmarx-java.yml'

variables:
  APP_NAME: ecom-sdk-php

checkmarx:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

push:
  stage: deploy
  script:
    - git config --global user.email "ecom@raiffeisen.ru"
    - git config --global user.name "user-ecom-git"
    - git push https://$OPEN_SOURCE_GITHUB_LOGIN:$OPEN_SOURCE_GITHUB_TOKEN_PHP@github.com/Raiffeisen-DGTL/$APP_NAME.git HEAD:main --force
  only:
    - main
